### ISSUE TITLE
Error 3.1.0

### ISSUE THREAD

**Issue by Mickyc94** [XGProyect/XG-Proyect-v3.x.x#300]
**Describe the bug**

I have only tested with transport and colonize but when you send either cargo ship or try to colonise a new planet I get the following error;

"Uncaught Error: Class 'application\controllers\game\Timing' not found in D:\xampp\htdocs\application\controllers\game\movement.php:221 Stack trace: #0 D:\xampp\htdocs\application\controllers\game\movement.php(168): application\controllers\game\Movement->buildMovements() #1 D:\xampp\htdocs\application\controllers\game\movement.php(105): application\controllers\game\Movement->buildPage() #2 D:\xampp\htdocs\public\game.php(58): application\controllers\game\Movement->__construct() #3 {main} thrown
in D:\xampp\htdocs\application\controllers\game\movement.php on line 221
Error code: 1
Trace (Debug Log):
Where called: line of (in )
Where called: line of (in )
Where called: line of application\core\ErrorHandler (in )
Where called: line 91 of application\core\ErrorHandler (in D:\xampp\htdocs\application\core\ErrorHandler.php)
Where called: line 77 of application\libraries\DebugLib (in D:\xampp\htdocs\application\core\ErrorHandler.php)
Where called: line 139 of application\libraries\DebugLib (in D:\xampp\htdocs\application\libraries\DebugLib.php)"

(It only gives this error until the fleet movement is complete and cannot access fleet movement page until its whatever task is complete, other than fleets everything seems to work just fine)

 - OS: Windows 10
 - Browser: Firefox
 - PHP Version:  7.1.19
 - MySQL Version: MariaDB

**Comment by Mickyc94** [comment]
appears to be fine in phase 4 so will just continue to use that
