### ISSUE TITLE
Expedition Error when finished [3.4]

### ISSUE THREAD

**Issue by manuelkamp** [XGProyect/XG-Proyect-v3.x.x#529]
**Describe the bug**
Expedition finishing results in an error.

**To Reproduce**
1. Start expedition, wait until finished
2. Error occurs
 
 **Server (please complete the following information):**
 - PHP Version: 8.1

**Additional context**
`Uncaught Error: Call to undefined method App\Libraries\Missions\Missions::loadLang() in /var/www/html/app/Libraries/Missions/Expedition.php:30 Stack trace: #0 /var/www/html/app/Libraries/MissionControlLib.php(75): App\Libraries\Missions\Expedition->__construct() #1 /var/www/html/app/Libraries/MissionControlLib.php(24): App\Libraries\MissionControlLib->processMissions() #2 /var/www/html/app/Libraries/UpdatesLibrary.php(130): App\Libraries\MissionControlLib->arrivingFleets() #3 /var/www/html/app/Libraries/UpdatesLibrary.php(35): App\Libraries\UpdatesLibrary->updateFleets() #4 /var/www/html/app/Core/Common.php(134): App\Libraries\UpdatesLibrary->__construct() #5 /var/www/html/app/Core/Common.php(52): App\Core\Common->setUpdates() #6 /var/www/html/public/game.php(11): App\Core\Common->bootUp() #7 {main} thrown in /var/www/html/app/Libraries/Missions/Expedition.php on line 30`

**Comment by FGServers** [comment]
Confirm this bug any mission
